apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazor-deployment
  labels:
    app: blazor
spec:
  replicas: 3
  template:
    metadata:
      name: blazor
      labels:
        app: blazor
    spec:
      containers:
      - name: blazor
        image: yuksektek.azurecr.io/oyuksektepeli/blazor:latest
        imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: blazor2


---

apiVersion: v1
kind: Service
metadata:
  name: blazor-service
spec:
  selector:
    app: blazor
  ports:
    - port: 80
  type: LoadBalancer
  
  